#mysql
mysql:
  write-url: jdbc:mysql://10.0.66.94:3306/csxdev_user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull
  write-username: root
  write-password: csxdev
  read-url: jdbc:mysql://10.0.66.94:3306/csxdev_common?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull
  read-username: root
  read-password: csxdev
  filters: stat
  maxActive: 5
  initialSize: 2
  maxWait: 60000
  minIdle: 1
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxOpenPreparedStatements: 20
#redis
redis:
  ip: 127.0.0.1
  port: 6379
  maxTotal: 20
  maxIdle: 10
  testOnBorrow: true
  password: xceof
  timeout: 5000

spring.dubbo:
  scan: com.muy.dubbo.order
  application:
   name: muy-dubbo-order
  registry:
   address: zookeeper://127.0.0.1:2181
   protocol :
       prot : 21180
       name  : dubbo

server:
  port: 8084
security:
  user:
    password: pwd
    name: user
endpoints:
  actuator:
    enabled: true
management:
  security:
    enabled: false

